import "server-only";

import type { EnvironmentSource } from "./environment-source";
import { parseServerEnvironment, type ServerEnvironment } from "./server-environment-parser";

function readServerSource(): EnvironmentSource {
  return {
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    AUTH_EMAIL_CONFIRMATION_REQUIRED: process.env.AUTH_EMAIL_CONFIRMATION_REQUIRED,
    AUTH_OAUTH_AZURE_ENABLED: process.env.AUTH_OAUTH_AZURE_ENABLED,
    AUTH_OAUTH_GITHUB_ENABLED: process.env.AUTH_OAUTH_GITHUB_ENABLED,
    AUTH_OAUTH_GOOGLE_ENABLED: process.env.AUTH_OAUTH_GOOGLE_ENABLED,
    SUPABASE_SECRET_KEY: process.env.SUPABASE_SECRET_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    DEPLOYMENT_PROFILE: process.env.DEPLOYMENT_PROFILE,
    ENABLE_CHILD_PROFILES: process.env.ENABLE_CHILD_PROFILES,
    ENABLE_PUBLIC_CHILD_CONTENT: process.env.ENABLE_PUBLIC_CHILD_CONTENT,
    ENABLE_FREE_TEXT_GAME_CHAT: process.env.ENABLE_FREE_TEXT_GAME_CHAT,
    APP_ENCRYPTION_KEY: process.env.APP_ENCRYPTION_KEY,
    GUEST_TOKEN_SIGNING_KEY: process.env.GUEST_TOKEN_SIGNING_KEY,
    NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY,
    AUDIT_EVENT_RETENTION_DAYS: process.env.AUDIT_EVENT_RETENTION_DAYS,
    DELETION_GRACE_PERIOD_DAYS: process.env.DELETION_GRACE_PERIOD_DAYS,
    EXPORT_DOWNLOAD_RETENTION_DAYS: process.env.EXPORT_DOWNLOAD_RETENTION_DAYS,
    GUEST_SESSION_RETENTION_HOURS: process.env.GUEST_SESSION_RETENTION_HOURS,
    PROFILE_SESSION_TTL_MINUTES: process.env.PROFILE_SESSION_TTL_MINUTES,
    RATE_LIMIT_DESTRUCTIVE_REQUEST_ATTEMPTS: process.env.RATE_LIMIT_DESTRUCTIVE_REQUEST_ATTEMPTS,
    RATE_LIMIT_GUEST_CREATION_ATTEMPTS: process.env.RATE_LIMIT_GUEST_CREATION_ATTEMPTS,
    RATE_LIMIT_PASSWORD_RESET_ATTEMPTS: process.env.RATE_LIMIT_PASSWORD_RESET_ATTEMPTS,
    RATE_LIMIT_PROFILE_PIN_ATTEMPTS: process.env.RATE_LIMIT_PROFILE_PIN_ATTEMPTS,
    RATE_LIMIT_SIGNUP_ATTEMPTS: process.env.RATE_LIMIT_SIGNUP_ATTEMPTS,
    RATE_LIMIT_WINDOW_SECONDS: process.env.RATE_LIMIT_WINDOW_SECONDS,
    PARENTAL_CONSENT_MODE: process.env.PARENTAL_CONSENT_MODE,
    PARENTAL_CONSENT_VERIFIER_API_KEY: process.env.PARENTAL_CONSENT_VERIFIER_API_KEY,
    PARENTAL_CONSENT_VERIFIER_URL: process.env.PARENTAL_CONSENT_VERIFIER_URL,
    VERCEL: process.env.VERCEL,
  };
}

export function getServerEnvironment(
  source: EnvironmentSource = readServerSource(),
): ServerEnvironment {
  return parseServerEnvironment(source);
}

export type {
  DeploymentProfile,
  OAuthProvider,
  ParentalConsentMode,
  PrivacyRetentionConfiguration,
  RateLimitConfiguration,
  ServerEnvironment,
} from "./server-environment-parser";
